[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
BuckyBank = "5uykfXh94mwTz2Vxb2Y7RpntvanSkcWq4hENoDM4duVf"

[programs.localnet]
BuckyBank = "5uykfXh94mwTz2Vxb2Y7RpntvanSkcWq4hENoDM4duVf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "../node_modules/.bin/jest --preset ts-jest"
